### ISSUE TITLE
bump query builder

### ISSUE THREAD

**Issue by grfx1985** [SixiS/jquery_query_builder-rails#2]
any chance of bumping to newer version than 2.3.3 ?

**Comment by grfx1985** [comment]
usage of value separator would be fantastic

**Comment by SixiS** [comment]
Hey - thanks for the issue.
Will look into bumping all the versions - make take me a couple days just to make sure everything still works.

If you are keen to test it so long the changes are on a branch:
https://github.com/SixiS/jquery_query_builder-rails/tree/query_builder_2_4_3

**Comment by grfx1985** [comment]
will give it a try :+1:  thanks!

**Comment by grfx1985** [comment]
so far separator works :)

**Comment by grfx1985** [comment]
if You are planning to adjust it to the newer version please take under consideration the internationalization side of this plugin, it would be quite usefull to use the lang_code option ;)

**Comment by SixiS** [comment]
@grfx1985 Master has the new version along with the i18n files.
The new stuff is on gem version 0.4.0
Thanks again for all the feedback!
